### ISSUE TITLE
Client collection messageQueue Not Protected for Multithreading

### ISSUE THREAD

**Issue by diegolazzz** [nmosafi/aspComet#17]
Stack trace:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Queue`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at AspComet.Client.get_HasPendingMessages()
   at AspComet.MessageHandlers.MetaConnectHandler.HandleMessage(Message request)
   at AspComet.MessagesProcessor.Process(Message message)
   at AspComet.MessagesProcessor.Process(IEnumerable`1 messages)
   at AspComet.MessageBus.HandleMessages(Message[] messages, ICometAsyncResult asyncResult)
   at AspComet.CometHttpHandler.BeginProcessRequest(HttpContextBase context, AsyncCallback callback, Object asyncState)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by diegolazzz** [comment]
Possible solution:

public bool HasPendingMessages
        {
            get {
                    lock (this.syncRoot)
                    {
                        return this.messageQueue.Any();
                    }       
                }
        }
